#!/bin/sh
# This script executes specified js file using jjs utility

if [ "$#" -eq "0" ]
then
  cat <<HELP
        This script executes specified js file using jjs utility (make sure jjs is in PATH).
    It loads the js script in the first argument and passes the rest arguments to the js script
    i.e.: ./jmvcc jmvc/script/controller todo my_app
    
    Usage:
        ./jmvcc FILE [ARGS] - executes FILE using jjs [pasing ARGS to the FILE script]
    
    For detailed help execute ./jmvcc --help [-h, -?]
HELP
    exit 127
fi

if [ $1 = "-h" -o $1 = "-?" -o $1 = "--help" ]
then
    cat <<MORE_HELP
        This script executes specified js file using jjs utility (make sure jjs is in PATH).
    It loads the js script in the first argument and passes the rest arguments to the js script
    i.e.: ./jmvcc jmvc/script/controller todo my_app

    Usage:
        ./jmvcc FILE [ARGS] - executes FILE using jjs [pasing ARGS to the FILE script]

    JavascriptMVCConsole script usage:

        ./jmvcc jmvc/update   - Updates jmvc core (jmvc folder) from the repository
                                    (http://bitbucket.org/Ingvord/javascriptmvc-1.5.x)
        ./jmvcc jmvc/engine install NAME    - Installs an engine from the repository
                                    (http://bitbucket.org/Ingvord/jmvc-engines)
        ./jmvcc jmvc/plugin install NAME    - Installs a plugin from the repository
                                    (http://bitbucket.org/Ingvord/jmvc-plugins)

        ./jmvcc jmvc/generate/app NAME    - Creates a new JavaScriptMVC application
        ./jmvcc jmvc/generate/app_js APP  - Generates apps/[APP].js and apps/[APP]/test.js files
        ./jmvcc jmvc/generate/engine NAME [APP]       - Generates a new engine skeleton
        ./jmvcc jmvc/generate/fixture METHOD URL [APP]  - Generates a fixture
        ./jmvcc jmvc/generate/page APP PAGE           - Generates a page for the application
        ./jmvcc jmvc/generate/controller NAME [APP]   - Generates a Controller file
        ./jmvcc jmvc/generate/model TYPE NAME [APP]   - Generates a Model file
        ./jmvcc jmvc/generate/view NAME [APP]         - Generates a View file

    Calling any of these commands without arguments will show its usage, e.g. './jmvcc jmvc/generate/controller'

    Tp remove application or an entity from an application:

        ./jmvcc jmvc/remove/app APP                 - Removes APP
        ./jmvcc jmvc/remove/entity TYPE NAME [APP]  - Removes corresponding entity files, if APP provided removes from APP

    The following is used to create a production.js file for an application:

        ./jmvcc apps/NAME/compress.js - Compress your application and generate documentation
MORE_HELP
  exit 127
fi

echo `which jjs`

SCRIPT_FILE=$1
shift
jjs -classpath .:jmvc/rhino/compiler.jar:jmvc/rhino/compiler-integration.jar -scripting $SCRIPT_FILE -- $*
